title: Browsers
description: Installs browsers
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Installing Thorium', option: "thorium"}
  - !software:
      option: "thorium"
      name: "thorium"
      source: chocolatey

  - !writeStatus: {status: 'Installing LibreWolf', option: "librewolf"}
  - !software:
      option: "librewolf"
      name: "librewolf"
      source: chocolatey

  - !writeStatus: {status: 'Installing Zen Browser)', option: "zenbrowser"}
  - !software:
      option: "zenbrowser"
      name: "zen-browser"
      source: chocolatey

  - !writeStatus: {status: 'Installing Brave', option: "brave"}
  - !software:
      option: "brave"
      name: "brave"
      source: chocolatey