title: Dark Mode
actions:
  - !writeStatus: {status: 'Enabling Dark Mode'}
  
  - !registryValue:
      path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
      value: 'AppsUseLightTheme'
      type: REG_DWORD
      data: '0'
      
  - !registryValue:
      path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
      value: 'SystemUsesLightTheme'
      type: REG_DWORD
      data: '0'